const notes = {
  1: "Ouverture : la migration est présentée comme une route gouvernée entre un état legacy et un état moderne. Préciser que le projet réel réalisé chez CGI est confidentiel et que le deck représente une version démo fictive et anonymisée. Sources : rapport, page de garde ; storyboard et source-map du dépôt.",
  2: "Annoncer les sept chapitres. La carte sert à donner au jury une trajectoire de lecture ; elle ne remplace pas le détail oral. Source : storyboard-18-slides.md.",
  3: "Raconter le déclencheur : un grand client aérien vise une migration cloud à horizon fin 2027. Le portefeuille legacy doit évoluer vers Azure tout en conservant la disponibilité des applications. Ne citer aucun nom client. Sources : rapport pp. 14–22 ; contexte fourni par le porteur du projet ; source-map.",
  4: "Faire apparaître la tension réelle : les mêmes équipes gèrent maintenance, incidents, optimisation et migration progressive. La continuité fonctionnelle reste la priorité du client. Les risques visibles sont la perte de contexte, le rework, les décisions dispersées et les preuves difficiles à relier. Sources : rapport pp. 20–22 ; storyboard.",
  5: "Expliquer la bascule : les prompts et pratiques individuelles capitalisent un savoir utile, mais ne passent plus à l'échelle d'un portefeuille. La réflexion mène à une Migration Factory multi-agents avec validation humaine. Java/Spring Boot et Angular sont le périmètre démontré ; les autres écosystèmes restent une vision cible. Sources : rapport pp. 22, 41–51 et 84–85 ; source-map.",
  6: "Lire l'architecture de haut en bas : l'humain fixe l'intention et autorise, l'orchestrateur porte l'état et les transitions, les agents produisent des propositions, les services déterministes exécutent et vérifient, le registre conserve les preuves. Sources : rapport pp. 41–51.",
  7: "Montrer que Java et Angular n'ont pas la même toolchain. Ils partagent toutefois les contrats de gouvernance : état, gate, checksum, validation et historique. Sources : rapport pp. 41–51 et 52–65.",
  8: "Décrire le parcours comme une progression par états. Les gates structurent les passages critiques et chaque transformation revient vers une preuve de validation. Source : rapport pp. 41–51 et 52–65 ; matrice de références de la démo.",
  9: "Présenter Java/Spring Boot comme le parcours de référence le plus mature : Spring Boot 2.1, 2.7, 3.5 et 4.0 avec Java 11, 17 et 21, Maven et OpenRewrite. Ne pas transformer cette trajectoire en promesse de couverture universelle. Sources : rapport pp. 52–64 et 70–79.",
  10: "Préciser les frontières Angular : 18→19 et 19→20 sont scellées ; 20→21 est préparée mais non démarrée. Une migration 11→21 n'est pas démontrée. Sources : rapport pp. 53–55, 65–66 et 70–79 ; source-map.",
  11: "Les agents sont spécialisés et bornés : analyse, review, planification, transformation, réparation et assistance. Aucun agent ne reçoit un accès libre au terminal ou au système de fichiers. La décision sensible reste humaine. Sources : rapport pp. 43–51 et 61–64.",
  12: "Décrire la réparation comme un changement contrôlé : échec gelé, contexte réuni, proposition, review, décision humaine, application isolée, build/test et revalidation. Les checksums, tentatives bornées et historiques évitent le retry aveugle. Sources : rapport pp. 50–51, 63–65 et 78–79 ; matrice de références de la démo.",
  13: "Faire la démonstration autour d'une seule décision : inspecter la correction Angular G10, vérifier la preuve, puis approuver, modifier ou rejeter. Préciser que l'interface est locale, déterministe, anonymisée et basée sur des états préparés ; elle ne connecte pas le backend CGI, Maven, npm ou Azure. Sources : DEMO-RECORDING.md et source-reference-matrix.md.",
  14: "Présenter uniquement les observations disponibles : 607 tests backend réussis et 4 ignorés ; contrôles frontend de type, conformité et build validés ; baseline frontend de 12 à 11 échecs après intégration ; transitions Angular 18→19 et 19→20 scellées. Ce sont des preuves ponctuelles, pas un benchmark global. Sources : rapport p. 66 et pp. 70–81.",
  15: "Relier chaque difficulté à la réponse technique décrite dans le rapport : diff structuré, manifeste backend, catalogue de profils versionné et base SQLite autoritaire réconciliée. Sources : rapport pp. 65 et 81–84.",
  16: "Assumer les limites : authentification et rôles non livrés, benchmark manuel contrôlé absent, CI commune absente, couverture Angular incomplète, coûts et durées LLM non consolidés. Présenter sécurité, instrumentation, benchmark et nouveaux écosystèmes comme perspectives. Sources : rapport pp. 82–85.",
  17: "Conclure sur le principe architectural : les agents raisonnent et proposent ; les services déterministes exécutent et vérifient ; l'humain contrôle les décisions sensibles. La contribution est une automatisation gouvernée, traçable et revalidable, pas une autonomie totale. Sources : rapport pp. 84–85.",
  18: "Ouvrir la discussion sur les choix d'architecture, les preuves et les limites assumées. Ne pas introduire de nouveau résultat. Source : storyboard-18-slides.md.",
};

export function speakerNotes(slideNumber) {
  return notes[slideNumber] ?? "Version démo fictive et anonymisée du projet de migration. Sources détaillées dans docs/presentation/source-map.md.";
}
